### PR TITLE
Added the VariateSettings and Combination objects (Although I didn't …

### PR DESCRIPTION
**Pull request by Poonwahj**
…fill them out completely) so I could get Click and Open reports for Combo Campaigns.

These changes are useful if you're creating AB tests and need to get child campaigns of campaigns.

### CODE REVIEW

**Comment by Poonwahj** [comment]
These changes are preliminary changes that will allow users of MailChimp.Net to query out Combination Campaigns within Campaigns.  I didn't completely fill out the models as I didn't need them, but I assumed this would be the beginning of changes that would address new features in Mailchimp that were added in Oct/Nov 2017.

**Comment by brandonseydel** [comment]
Change to IEnumerable and it looks good

**Comment by Poonwahj** [comment]
Done and done.  I also noticed that some classes use IList<> and do not initialize them in the constructor (like PRODUCT) and some use IEnumerable and do (Like report, which uses Hashsets), if you have a preference I'll use that.

**Comment by brandonseydel** [comment]
Usually the lowest level implementation on the class instantiated with the lowest level non abstract.  If you want to clean up some code that would be great.
________________________________

**Comment by Poonwahj** [comment]
I will have to come back as duty calls, but thanks for putting this project together, it's much used, much appreciated and great work!!!

**Pull request merged**
