### PR TITLE
Expose Hash through MemberLogic to ease batch operations including cr…

### PR DESCRIPTION
**Pull request by manicfiddler**
…eating List Members as you need to provide the hash of the email address

### CODE REVIEW

**Comment by brandonseydel** [comment]
I would like to abstract this out so people don't actually have to call hash on emails and just do that in the logic layer itself.

**Comment by brandonseydel** [comment]
What use case do you need this exposed so we can think of a better way to handle this.  In the batch logic layer?

**Comment by manicfiddler** [comment]
Seemed the easiest way to expose it.....when adding list members as part of a batch request I needed to provide the email hash as part of the Path of the batch operation

**Comment by brandonseydel** [comment]
Can you narrow down the method you are talking about so I can take a look.  I am not sure what layer you are invoking.

**Comment by manicfiddler** [comment]
Sorry Brandon, not really sure what you are asking me here, but I think this is it:

I am trying to create all my list members as a batch operation to speed things up.

When you use MemberLogic.AddOrUpdateAsync it internally calls this.Hash to create the full URL for the member to create.

When building a list of Batch operations I need to build the URL myself.

Granted I could have just copied the Hash method out to my client code but it seemed simpler and harmless to expose it through IMemberLogic

**Comment by brandonseydel** [comment]
Should we expose this on a base interface for all logic layers?

**Comment by brandonseydel** [comment]
I just put in a language feature request to Mads for your emailAddress push
I was like why can't i just do this
public string Hash(string emailAddress = emailAddress?.ToLower())

**Pull request merged**
