### PR TITLE
Batches GetOperationsResponse implemented

### LINKED ISSUE #227: Batches - there is no GetBatchResults method
A method to get results from ResponseUrl

Endpoint /batches/{batchId} returns response url among other information like TotalOperations, ErroredOperations, etc. 
Get to this url downloads tar.gz file which contains .json file with results for each BatchOperation and we can see what was successful and what failed

### PR DESCRIPTION
**Pull request by etaletovic**
Closes #227

### CODE REVIEW

**Comment by brandonseydel** [comment]
I don't like adding third party requirements.  Please remove.

**Comment by etaletovic** [comment]
Hi Brandon,
What do you mean by third party requirements? Is it due to SharpZipLib package or..?

**Comment by brandonseydel** [comment]
Yes can't we just use gzipstream

**Comment by brandonseydel** [comment]
After this merge a new release will be going out to nuget.

**Comment by etaletovic** [comment]
I don't think there is built in .tar support in .Net.
I am already using GZipStream to decompress the file with responses. Mailchimp returns a link to a .tar.gz file.

**Comment by etaletovic** [comment]
If it's a no to use third party library, since MailChimp doesn't have an endpoint to return this kind of information then I guess we don't need to add it.

**Pull request closed without merging**
