### PR TITLE
Enable Tags to be submitted when adding/updating members

### LINKED ISSUE #351: Support for adding Tags to Members
Hi, can we be expecting support for adding tags to members in Members.AddOrUpdateAsync?
Currently the Tag data is not added even though it is present in the Member object sent to the method.

### PR DESCRIPTION
**Pull request by samueldjack**
This should fix #351

### CODE REVIEW

**Comment by knockoutpill** [comment]
Has this been released? I'm using 3.4.0 and calling Members.AddOrUpdateAsync(listId, member) with this member doesn't seem to work: 

            var member = new Member
            {
                EmailAddress = emailAddress,
                Status = Status.Pending,
                MergeFields = new Dictionary<string, object>
                {
                    {"FNAME", firstName},
                    {"LNAME", lastName}
                },
                Tags = tags 
            };

(Where tags is a List<MemberTag>).

**Comment by knockoutpill** [comment]
The latest nuget package seems to still be 3.4.0, which doesn't contain this fix. Will the nuget package be updated soon..?

**Comment by AlanGonzalo** [comment]
Hello, I'm using the lastest version of the package and still not able to add tags to members. Any update of this?

**Comment by knockoutpill** [comment]
> Hello, I'm using the lastest version of the package and still not able to add tags to members. Any update of this?

Same here AlanGonzalo. Are you using version 3.4.0? The next version after that should have it, whenever that nuget package gets released.

**Comment by rjacquemin** [comment]
Waiting for the release as well !

Thanks in advance

**Comment by ramedey** [comment]
Hi, 

I also need this feature. Do you have an estimation of when the NuGet package will get released?

Thanks.

**Comment by knockoutpill** [comment]
> Hi all,
> I updated to the newest version 3.5.0, but still can't tag users. Have any of you tried by any chances?

Hi! I heard today that the nuget package had been updated. Didn't have time to test it myself though. I'll test it on Monday and report back here unless you already have found a solution.

**Comment by knockoutpill** [comment]
> Hi all,
> I updated to the newest version 3.5.0, but still can't tag users. Have any of you tried by any chances?

Hi! It works for me.

**Comment by brandonseydel** [comment]
It looks like an improper serialization of the the member tags.

**Comment by brandonseydel** [comment]
I just reran the unit tests and it worked fine?

**Comment by knockoutpill** [comment]
> I just reran the unit tests and it worked fine?

Yep. Works for me, like I said.

**Pull request merged**
